### ISSUE TITLE
Does not include Tools

### ISSUE THREAD

**Issue by gerritdevriese** [gucci-on-fleek/Stardew-Valley-Item-Finder#1]
### Describe the bug
The Item Finder does not include any items of type Tool (Hoe, Axe, Watering Can, etc...)
Which is unfortunate, because I seem to have misplaced my Watering Can 🙃

### Browser and OS
Tested on both Arch Linux with Firefox 101.0.1 and Windows 10 with Chrome, both have this problem.

### Save file
Tested with two separate save files, issue appears in both.

**Comment by gucci-on-fleek** [comment]
The fix should be live now. You'll probably need to do a hard refresh (`Ctrl+Shift+R`) since the caching is pretty aggressive.

And thanks for the report!
